---
settings:
  name: NetApp public and hybrid cloud solutions
  internal:
    pdf_enabled: true
    lipi_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
    lipi_enabled: true
  pdf:
    gen-type: named-only
    zip-level: 1
    zip-filename: netapp-solutions-cloud.zip
  langs: fr-fr,us-en,de-de,es-es,it-it,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Solutions de cloud public et hybride
    url: "/index.html"
  - title: Quoi de neuf
    url: "/whats-new.html"
  - section: ehc
  - section: rhhc
  - title: Vidéos
    url: "/videos/index.html"
    entries:
    - title: Cloud hybride AWS
      url: "/videos/hmc-aws-videos.html"
    - title: Cloud hybride Azure
      url: "/videos/hmc-azure-videos.html"
    - title: Cloud hybride OpenShift
      url: "/videos/hmc-openshift-videos.html"
  - title: Blogs
    url: "/blogs.html"
  - title: Mentions légales
    url: "/legal-notices.html"
product-family:
  name: NetApp solutions
  repo: netapp-solutions-family
