---
sidebar: sidebar 
permalink: google/gcp-gcnv-firewall.html 
keywords: tcp, nfs, smb share, kerberos, active directory, dns 
summary: Google Cloud NetApp Volumes expose plusieurs ports TCP pour servir les partages NFS et SMB. 
---
= Pare-feu
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Google Cloud NetApp Volumes expose plusieurs ports TCP pour servir les partages NFS et SMB :

* https://docs.cloud.google.com/netapp/volumes/docs/connect-clients/connect-nfs-clients#firewall_rules_for_nfs_volumes_access["Ports requis pour l'accès NFS"^]
* https://docs.cloud.google.com/netapp/volumes/docs/connect-clients/connect-smb-clients#firewall_rules_for_smb_volumes_access["Ports requis pour l'accès SMB"^]


De plus, les configurations SMB, NFS avec LDAP, y compris Kerberos, et à double protocole nécessitent un accès à un domaine Windows Active Directory. Les connexions Active Directory doivent être https://docs.cloud.google.com/netapp/volumes/docs/configure-and-use/active-directory/create-ad-policy["configuré"^] établies par région. Les contrôleurs de domaine Active Directory (DC) sont identifiés en utilisant https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-adts/7fcdce70-5205-44d6-9c3a-260e616a2f04["Découverte de DC basée sur DNS"^] les serveurs DNS spécifiés. Tous les DC renvoyés sont utilisés. La liste des DC éligibles peut être limitée en spécifiant un site Active Directory.

Google Cloud NetApp Volumes utilise des adresses IP de la plage CIDR allouée avec la `gcloud compute address` commande lorsque https://docs.cloud.google.com/netapp/volumes/docs/plan-and-prepare/networking#configure_private_services_access["intégration de Google Cloud NetApp Volumes"^]. Vous pouvez utiliser cette plage CIDR comme adresses source pour configurer les pare-feu entrants de vos contrôleurs de domaine Active Directory.

Les contrôleurs de domaine Active Directory doivent https://docs.cloud.google.com/netapp/volumes/docs/plan-and-prepare/security-considerations["exposer les ports aux CIDR Google Cloud NetApp Volumes comme mentionné ici"^].
